import type { CalibrationEntry, CalibrationTable, EngineId } from '@marlo/schema';
import { findRule } from '@marlo/act';

/**
 * Renders the calibration table as markdown, for `calibration/README.md`.
 *
 * Every number here comes from the table. Nothing is computed a second time and nothing
 * is rounded in a way that flatters: a rate is shown to two decimals, and an absent
 * measurement is shown as an em-free dash placeholder rather than as 0, because
 * precision over zero predictions is not zero precision.
 */

function rate(value: number | null): string {
  return value === null ? 'not measured' : value.toFixed(2);
}

function pct(value: number | null): string {
  return value === null ? 'not measured' : `${(value * 100).toFixed(1)}%`;
}

const ENGINE_LABELS: Readonly<Record<EngineId, string>> = Object.freeze({
  marlo: 'Marlo',
  'axe-core': 'axe-core',
  alfa: 'Alfa',
  htmlcs: 'HTML CodeSniffer',
});

export function renderCalibrationMarkdown(table: CalibrationTable): string {
  const lines: string[] = [];

  lines.push('# The calibration table');
  lines.push('');
  lines.push(
    'Generated by `pnpm calibrate`. Do not edit: a hand edit here is a published error rate ' +
      'turning into a marketing number, and CI fails on a table that disagrees with the harness.',
  );
  lines.push('');
  lines.push(`Generated ${table.generated} from corpus retrieved ${table.corpus.retrieved}.`);
  lines.push(
    `Renderer: \`${table.renderer}\`. Commit: ${table.commit === null ? 'a dirty tree' : `\`${table.commit}\``}.`,
  );
  lines.push('');

  lines.push('## What the two views mean');
  lines.push('');
  lines.push(
    "**ACT consistency** is W3C's official verdict, from `pages/implementations/mapping.md`. " +
      'Under that protocol `cantTell` is an allowed outcome for every example type, so an ' +
      'implementation that never commits grades as `consistent` while telling a developer nothing.',
  );
  lines.push('');
  lines.push(
    '**Strict precision and recall** count `cantTell` as no detection. That is what a user ' +
      'experiences: whether the violation will be found, and whether a clean report means clean.',
  );
  lines.push('');
  lines.push(
    'The **flattered** column marks rules where the two disagree in the direction that matters: ' +
      'officially consistent, and strict recall below 0.5. That is the column nobody publishes, ' +
      'and it is why this table has two halves. See [DECISIONS.md D-004](../DECISIONS.md#d-004).',
  );
  lines.push('');

  lines.push('## Coverage');
  lines.push('');
  lines.push(
    `Marlo implements **${String(table.coverage.implemented)} of ${String(table.coverage.publishedActRules)} published ACT rules**.`,
  );
  lines.push('');
  lines.push(
    `Of those, ${String(table.coverage.calibratable)} can be measured against official test cases.`,
  );
  if (table.coverage.implementedButUnmeasurable.length > 0) {
    lines.push('');
    lines.push(
      `${String(table.coverage.implementedButUnmeasurable.length)} implemented rule(s) have no ` +
        `official test cases and therefore cannot be calibrated: ` +
        `${table.coverage.implementedButUnmeasurable.map((r) => `\`${r}\``).join(', ')}. ` +
        'They are named rather than omitted, because leaving them out would overstate coverage ' +
        'and counting them as calibrated would overstate accuracy.',
    );
  }
  lines.push('');

  lines.push("## Marlo's own numbers");
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| Strict precision | ${rate(table.aggregate.strictPrecision)} |`);
  lines.push(`| Strict recall | ${rate(table.aggregate.strictRecall)} |`);
  lines.push(`| **False positive rate** | **${pct(table.aggregate.falsePositiveRate)}** |`);
  lines.push(`| Official test cases behind these | ${String(table.aggregate.sampleSize)} |`);
  lines.push('');
  lines.push(
    'The false positive rate is the number this project would most like to be small and is ' +
      'published whatever it is. A regression in it fails CI.',
  );
  lines.push('');

  lines.push('## Engines');
  lines.push('');
  lines.push('| Engine | Version | ACT rules claimed |');
  lines.push('|---|---|---|');
  for (const engine of table.engines) {
    lines.push(
      `| ${ENGINE_LABELS[engine.id]} | \`${engine.version}\` | ${String(engine.mappedRules)} |`,
    );
  }
  lines.push('');

  lines.push('## Per rule, per engine');
  lines.push('');
  lines.push(
    'Rules are listed in ACT identifier order. An engine with no mapping for a rule is omitted ' +
      'from that rule rather than shown as zero, because having no opinion and being wrong are ' +
      'different things.',
  );
  lines.push('');
  lines.push(
    '| ACT rule | Engine | Mapping | ACT verdict | Automation | Strict P | Strict R | cantTell (fail/pass) | Flattered |',
  );
  lines.push('|---|---|---|---|---|---|---|---|---|');

  const byRule = new Map<string, CalibrationEntry[]>();
  for (const entry of table.entries) {
    const list = byRule.get(entry.actRuleId) ?? [];
    list.push(entry);
    byRule.set(entry.actRuleId, list);
  }

  for (const actRuleId of [...byRule.keys()].sort()) {
    const entries = (byRule.get(actRuleId) ?? []).filter((e) => e.mappingKind !== 'none');
    if (entries.length === 0) continue;
    const rule = findRule(actRuleId);
    for (const entry of entries.sort((a, b) => a.engine.localeCompare(b.engine))) {
      lines.push(
        [
          `| [\`${actRuleId}\`](https://act-rules.github.io/rules/${actRuleId})`,
          ENGINE_LABELS[entry.engine],
          entry.mappingKind,
          entry.act.consistency,
          entry.act.automation,
          rate(entry.strict.precision),
          rate(entry.strict.recall),
          `${String(entry.strict.cantTellOnFailed)}/${String(entry.strict.cantTellOnPassed)}`,
          entry.flatteredByProtocol ? '**yes**' : 'no',
        ].join(' | ') + ' |',
      );
    }
    if (rule !== undefined) {
      lines.push(`| | | | | | | | | ${rule.name} |`);
    }
  }
  lines.push('');

  lines.push('## Routing');
  lines.push('');
  lines.push(
    'Which engine reports each rule, and whether the measurement clears the auto-fix threshold ' +
      `of ${rate(table.autoFixThreshold.minStrictPrecision)} strict precision over at least ` +
      `${String(table.autoFixThreshold.minSampleSize)} test cases.`,
  );
  lines.push('');
  lines.push('| ACT rule | Reported by | Why | Auto-fix permitted |');
  lines.push('|---|---|---|---|');
  for (const decision of [...table.routing].sort((a, b) =>
    a.actRuleId.localeCompare(b.actRuleId),
  )) {
    if (decision.chosen === null && decision.reason === 'no-implementer') continue;
    lines.push(
      `| \`${decision.actRuleId}\` | ${decision.chosen === null ? 'nobody' : ENGINE_LABELS[decision.chosen]} | ${decision.reason} | ${decision.autoFixPermitted ? 'yes' : 'no'} |`,
    );
  }
  lines.push('');

  const flattered = table.entries.filter((e) => e.flatteredByProtocol);
  lines.push('## Where the official protocol flatters an engine');
  lines.push('');
  if (flattered.length === 0) {
    lines.push(
      'No entry in this table is officially consistent while having strict recall below 0.5.',
    );
  } else {
    lines.push(
      `${String(flattered.length)} entr${flattered.length === 1 ? 'y' : 'ies'} would be reported as ` +
        'a correct implementation by the official protocol while missing more than half the ' +
        'violations a user would hit.',
    );
    lines.push('');
    lines.push('| ACT rule | Engine | ACT verdict | Strict recall |');
    lines.push('|---|---|---|---|');
    for (const entry of flattered.sort((a, b) => a.actRuleId.localeCompare(b.actRuleId))) {
      lines.push(
        `| \`${entry.actRuleId}\` | ${ENGINE_LABELS[entry.engine]} | ${entry.act.consistency} | ${rate(entry.strict.recall)} |`,
      );
    }
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}

/** A regression in any published number, for the CI gate. */
export interface Regression {
  readonly what: string;
  readonly before: string;
  readonly after: string;
}

/**
 * Compares a freshly generated table against the committed one.
 *
 * Fails on a worse false positive rate, worse aggregate precision or recall, a shrunken
 * coverage numerator, or a rule that stopped being routable. Does not fail on
 * improvements, and reports them, because a silent improvement is a number nobody
 * updated the README for.
 */
export function findRegressions(
  before: CalibrationTable,
  after: CalibrationTable,
): { readonly regressions: readonly Regression[]; readonly improvements: readonly Regression[] } {
  const regressions: Regression[] = [];
  const improvements: Regression[] = [];

  const compare = (
    what: string,
    a: number | null,
    b: number | null,
    higherIsBetter: boolean,
  ): void => {
    if (a === null || b === null) return;
    // A tolerance, because floating point arithmetic over pooled counts is not exact and
    // a diff of 1e-15 is not a regression.
    if (Math.abs(a - b) < 1e-9) return;
    const worse = higherIsBetter ? b < a : b > a;
    const record = { what, before: a.toFixed(4), after: b.toFixed(4) };
    if (worse) regressions.push(record);
    else improvements.push(record);
  };

  compare(
    'aggregate strict precision',
    before.aggregate.strictPrecision,
    after.aggregate.strictPrecision,
    true,
  );
  compare(
    'aggregate strict recall',
    before.aggregate.strictRecall,
    after.aggregate.strictRecall,
    true,
  );
  compare(
    'false positive rate',
    before.aggregate.falsePositiveRate,
    after.aggregate.falsePositiveRate,
    false,
  );

  if (after.coverage.implemented < before.coverage.implemented) {
    regressions.push({
      what: 'coverage numerator',
      before: String(before.coverage.implemented),
      after: String(after.coverage.implemented),
    });
  }

  const routedBefore = new Set(
    before.routing.filter((r) => r.chosen !== null).map((r) => r.actRuleId),
  );
  const routedAfter = new Set(
    after.routing.filter((r) => r.chosen !== null).map((r) => r.actRuleId),
  );
  for (const actRuleId of routedBefore) {
    if (!routedAfter.has(actRuleId)) {
      regressions.push({
        what: `rule ${actRuleId} is no longer routable to any engine`,
        before: 'routed',
        after: 'no engine',
      });
    }
  }

  return { regressions, improvements };
}
