/**
 * GENERATED FILE. Do not edit.
 *
 * Produced by scripts/generate-act-index.mjs from corpus/act/MANIFEST.json.
 * Regenerate with `pnpm act:index`; `pnpm act:index --check` fails if this
 * file is stale, and CI runs the check.
 *
 * It is generated rather than read at import time because @marlo/act is pure:
 * no filesystem, no network, asserted by dependency-cruiser. rules.generated.test.ts
 * reads the manifest and asserts this file agrees with it field by field, so the
 * two cannot drift.
 *
 * Corpus retrieved 2026-07-29. 94 published rules,
 * 91 with official test cases, 1134 test cases.
 */

/** One published ACT rule, as its own front matter declares it. */
export interface ActRuleRecord {
  /** Six-character identifier assigned by the ACT-Rules Community. */
  readonly id: string;
  readonly name: string;
  readonly ruleType: 'atomic' | 'composite';
  /** WCAG success criteria, extracted from accessibility_requirements. */
  readonly successCriteria: readonly string[];
  /**
   * Requirements that are not WCAG success criteria: techniques, ARIA terms,
   * European Accessibility Act references. Kept verbatim rather than dropped, so a
   * rule does not appear to map to fewer requirements than it does.
   */
  readonly otherRequirements: readonly string[];
  /** What the rule needs to look at. From the rule's input_aspects. */
  readonly inputAspects: readonly string[];
  /** Official test case counts. A total of zero means the rule is unmeasurable. */
  readonly testCases: {
    readonly passed: number;
    readonly failed: number;
    readonly inapplicable: number;
    readonly total: number;
  };
}

/** When the vendored corpus this index was generated from was retrieved. */
export const CORPUS_RETRIEVED = '2026-07-29';

/**
 * Every published ACT rule, sorted by identifier.
 *
 * The length of this array is the denominator of every coverage fraction Marlo
 * prints. It is not a configurable number.
 */
export const ACT_RULES: readonly ActRuleRecord[] = Object.freeze([
  Object.freeze({
    id: '047fe0',
    name: "Document has heading for non-repeated content",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:H69']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS Styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 9, failed: 4, inapplicable: 1, total: 14 }),
  }),
  Object.freeze({
    id: '09o5cg',
    name: "Text has enhanced contrast",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.3', '1.4.6']),
    otherRequirements: Object.freeze(['wcag-technique:G17', 'wcag-technique:G18']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 8, failed: 10, inapplicable: 11, total: 29 }),
  }),
  Object.freeze({
    id: '0ssw9k',
    name: "Scrollable content can be reached with sequential focus navigation",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.1.1', '2.1.3']),
    otherRequirements: Object.freeze(['wcag-technique:G202']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 2, failed: 2, inapplicable: 6, total: 10 }),
  }),
  Object.freeze({
    id: '0va7u6',
    name: "HTML images contain no text",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.5', '1.4.9']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 8, failed: 4, inapplicable: 2, total: 14 }),
  }),
  Object.freeze({
    id: '1a02b0',
    name: "Audio and visuals of video element have transcript",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.2.1', '1.2.8', '1.3.1']),
    otherRequirements: Object.freeze(['wcag-technique:G69']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 2, failed: 2, inapplicable: 1, total: 5 }),
  }),
  Object.freeze({
    id: '1ea59c',
    name: "Video element visual content has audio description",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G173', 'wcag-technique:G78', 'wcag-technique:G8']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 2, failed: 3, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: '1ec09b',
    name: "Video element visual content has strict accessible alternative",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.2.5']),
    otherRequirements: Object.freeze(['wcag-technique:G173', 'wcag-technique:G78', 'wcag-technique:G8']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 2, failed: 3, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: '23a2a8',
    name: "Image has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:G94', 'wcag-technique:G95']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 8, failed: 5, inapplicable: 5, total: 18 }),
  }),
  Object.freeze({
    id: '24afc2',
    name: "Important letter spacing in style attributes is wide enough",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.12']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 8, failed: 4, inapplicable: 4, total: 16 }),
  }),
  Object.freeze({
    id: '2779a5',
    name: "HTML page has non-empty title",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.2']),
    otherRequirements: Object.freeze(['wcag-technique:G88', 'wcag-technique:H25']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 5, failed: 5, inapplicable: 1, total: 11 }),
  }),
  Object.freeze({
    id: '2eb176',
    name: "Audio element content has transcript",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Language"]),
    testCases: Object.freeze({ passed: 3, failed: 6, inapplicable: 2, total: 11 }),
  }),
  Object.freeze({
    id: '2ee8b8',
    name: "Visible label is part of accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.5.3']),
    otherRequirements: Object.freeze(['wcag-technique:G208']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 6, failed: 3, inapplicable: 4, total: 13 }),
  }),
  Object.freeze({
    id: '2t702h',
    name: "Summary element has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 0, failed: 0, inapplicable: 0, total: 0 }),
  }),
  Object.freeze({
    id: '307n5z',
    name: "Element with presentational children has no focusable content",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 3, inapplicable: 1, total: 7 }),
  }),
  Object.freeze({
    id: '36b590',
    name: "Error message describes invalid form field value",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.3.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 3, failed: 5, inapplicable: 1, total: 9 }),
  }),
  Object.freeze({
    id: '3e12e1',
    name: "Block of repeated content is collapsible",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:SCR28']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS Styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 3, inapplicable: 1, total: 8 }),
  }),
  Object.freeze({
    id: '3ea0c8',
    name: "Id attribute value is unique",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:H93']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 3, inapplicable: 3, total: 10 }),
  }),
  Object.freeze({
    id: '46ca7f',
    name: "Element marked as decorative is not exposed",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility tree", "CSS styling", "DOM tree"]),
    testCases: Object.freeze({ passed: 6, failed: 3, inapplicable: 1, total: 10 }),
  }),
  Object.freeze({
    id: '4b1c6c',
    name: "Iframe elements with identical accessible names have equivalent purpose",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 10, failed: 4, inapplicable: 9, total: 23 }),
  }),
  Object.freeze({
    id: '4c31df',
    name: "Audio or video element that plays automatically has a control mechanism",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G170']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output"]),
    testCases: Object.freeze({ passed: 3, failed: 5, inapplicable: 3, total: 11 }),
  }),
  Object.freeze({
    id: '4e8ab6',
    name: "Element with role attribute has required states and properties",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze(['aria12:requiredState', 'wcag-technique:ARIA5']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 3, total: 8 }),
  }),
  Object.freeze({
    id: '59796f',
    name: "Image button has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1', '4.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:G94', 'wcag-technique:G95']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 4, failed: 3, inapplicable: 5, total: 12 }),
  }),
  Object.freeze({
    id: '59br37',
    name: "Zoomed text node is not clipped with CSS overflow",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 4, failed: 5, inapplicable: 5, total: 14 }),
  }),
  Object.freeze({
    id: '5b7ae0',
    name: "HTML page lang and xml:lang attributes have matching values",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree # The tree that HTML is parsed into."]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 7, total: 12 }),
  }),
  Object.freeze({
    id: '5c01ea',
    name: "ARIA state or property is permitted",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze(['aria12:state_property_processing', 'wcag-technique:ARIA5']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 11, failed: 2, inapplicable: 2, total: 15 }),
  }),
  Object.freeze({
    id: '5effbb',
    name: "Link in context is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.4', '2.4.9']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 9, failed: 6, inapplicable: 3, total: 18 }),
  }),
  Object.freeze({
    id: '5f99a7',
    name: "ARIA attribute is defined in WAI-ARIA",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 2, inapplicable: 1, total: 7 }),
  }),
  Object.freeze({
    id: '674b10',
    name: "Role attribute has valid value",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:ARIA4', 'wcag-technique:G108']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 5, total: 10 }),
  }),
  Object.freeze({
    id: '6a7281',
    name: "ARIA state or property has valid value",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze(['aria12:propcharacteristic_value']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 10, failed: 10, inapplicable: 4, total: 24 }),
  }),
  Object.freeze({
    id: '6cfa84',
    name: "Element with aria-hidden has no content in sequential focus navigation",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze(['using-aria:fourth']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 5, failed: 6, inapplicable: 3, total: 14 }),
  }),
  Object.freeze({
    id: '73f2c2',
    name: "Autocomplete attribute has valid value",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.5']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 8, failed: 5, inapplicable: 7, total: 20 }),
  }),
  Object.freeze({
    id: '7677a9',
    name: "Device motion based changes to the content can also be created from the user interface",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.5.4']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Accessibility tree"]),
    testCases: Object.freeze({ passed: 4, failed: 1, inapplicable: 1, total: 6 }),
  }),
  Object.freeze({
    id: '78fd32',
    name: "Important line height in style attributes is wide enough",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.12']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 10, failed: 6, inapplicable: 5, total: 21 }),
  }),
  Object.freeze({
    id: '7d6734',
    name: "SVG element with explicit role has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 3, total: 10 }),
  }),
  Object.freeze({
    id: '80af7b',
    name: "Focusable element has no keyboard trap",
    ruleType: 'composite',
    successCriteria: Object.freeze(['2.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:G21', 'wcag-text:cc5']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 6, failed: 6, inapplicable: 4, total: 16 }),
  }),
  Object.freeze({
    id: '80f0bf',
    name: "Audio or video element avoids automatically playing audio",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.4.2']),
    otherRequirements: Object.freeze(['wcag-technique:G170', 'wcag-technique:G171', 'wcag-technique:G60', 'wcag-text:cc5']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 3, total: 8 }),
  }),
  Object.freeze({
    id: '8fc3b6',
    name: "Object element rendering non-text content has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Accessibility Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 4, inapplicable: 6, total: 14 }),
  }),
  Object.freeze({
    id: '97a4e1',
    name: "Button has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 7, failed: 5, inapplicable: 5, total: 17 }),
  }),
  Object.freeze({
    id: '9bd38c',
    name: "Content has alternative for visual reference",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.3']),
    otherRequirements: Object.freeze(['wcag-technique:G96']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS Styling", "DOM Tree", "Language"]),
    testCases: Object.freeze({ passed: 15, failed: 4, inapplicable: 2, total: 21 }),
  }),
  Object.freeze({
    id: '9e45ec',
    name: "Important word spacing in style attributes is wide enough",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.12']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 8, failed: 4, inapplicable: 4, total: 16 }),
  }),
  Object.freeze({
    id: '9eb3f6',
    name: "Image filename is accessible name for image",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:G94', 'wcag-technique:G95']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 6, failed: 5, inapplicable: 4, total: 15 }),
  }),
  Object.freeze({
    id: 'a1b64e',
    name: "Focusable element has no keyboard trap via standard navigation",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 3, inapplicable: 4, total: 10 }),
  }),
  Object.freeze({
    id: 'a25f45',
    name: "Headers attribute specified on a cell refers to cells in the same table element",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1']),
    otherRequirements: Object.freeze(['wcag-technique:H43']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 8, failed: 4, inapplicable: 5, total: 17 }),
  }),
  Object.freeze({
    id: 'aaa1bf',
    name: "Audio or video element that plays automatically has no audio that lasts more than 3 seconds",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G60']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output"]),
    testCases: Object.freeze({ passed: 2, failed: 2, inapplicable: 3, total: 7 }),
  }),
  Object.freeze({
    id: 'ab4d13',
    name: "Video element content is media alternative for text",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 4, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: 'ac7dc6',
    name: "Video element visual-only content has description track",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:H96']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 1, inapplicable: 3, total: 5 }),
  }),
  Object.freeze({
    id: 'afb423',
    name: "Audio element content is media alternative for text",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 4, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: 'afw4f7',
    name: "Text has minimum contrast",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.3', '1.4.6']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 9, failed: 8, inapplicable: 11, total: 28 }),
  }),
  Object.freeze({
    id: 'aizyf1',
    name: "Link is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.9']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 4, failed: 5, inapplicable: 3, total: 12 }),
  }),
  Object.freeze({
    id: 'akn7bn',
    name: "Iframe with interactive elements is not excluded from tab-order",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.1.1', '2.1.3']),
    otherRequirements: Object.freeze(['wcag-technique:G202']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 4, failed: 1, inapplicable: 1, total: 6 }),
  }),
  Object.freeze({
    id: 'b20e66',
    name: "Links with identical accessible names have equivalent purpose",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.9']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 12, failed: 6, inapplicable: 3, total: 21 }),
  }),
  Object.freeze({
    id: 'b33eff',
    name: "Orientation of the page is not restricted using CSS transforms",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.4']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 2, failed: 3, inapplicable: 5, total: 10 }),
  }),
  Object.freeze({
    id: 'b40fd1',
    name: "Document has a landmark with non-repeated content",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 3, inapplicable: 1, total: 8 }),
  }),
  Object.freeze({
    id: 'b49b2e',
    name: "Heading is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.6']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 8, failed: 5, inapplicable: 4, total: 17 }),
  }),
  Object.freeze({
    id: 'b4f0c3',
    name: "Meta viewport allows for zoom",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.4.10', '1.4.4']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 4, total: 11 }),
  }),
  Object.freeze({
    id: 'b5c3f8',
    name: "HTML page has lang attribute",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:H57']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 1, failed: 4, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: 'bc4a75',
    name: "ARIA required owned elements",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 7, failed: 7, inapplicable: 5, total: 19 }),
  }),
  Object.freeze({
    id: 'bc659a',
    name: "Meta element has no refresh delay",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.2.1', '2.2.4', '3.2.5']),
    otherRequirements: Object.freeze(['wcag-technique:G110', 'wcag-technique:H76']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 8, total: 15 }),
  }),
  Object.freeze({
    id: 'bf051a',
    name: "HTML page lang attribute has valid language tag",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:H57']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 2, failed: 4, inapplicable: 1, total: 7 }),
  }),
  Object.freeze({
    id: 'bisz58',
    name: "Meta element has no refresh delay (no exception)",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.2.1', '2.2.4', '3.2.5']),
    otherRequirements: Object.freeze(['wcag-technique:G110', 'wcag-technique:H76']),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 2, failed: 4, inapplicable: 8, total: 14 }),
  }),
  Object.freeze({
    id: 'c249d5',
    name: "Device motion based changes to the content can be disabled",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.5.4']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Accessibility tree"]),
    testCases: Object.freeze({ passed: 3, failed: 1, inapplicable: 1, total: 5 }),
  }),
  Object.freeze({
    id: 'c3232f',
    name: "Video element visual-only content has accessible alternative",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.2.1']),
    otherRequirements: Object.freeze(['wcag-technique:G159', 'wcag-technique:G166']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 2, total: 9 }),
  }),
  Object.freeze({
    id: 'c487ae',
    name: "Link has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1', '2.4.4', '2.4.9', '4.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:G91']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 11, failed: 11, inapplicable: 6, total: 28 }),
  }),
  Object.freeze({
    id: 'c4a8a4',
    name: "HTML page title is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.2']),
    otherRequirements: Object.freeze(['wcag-technique:G88', 'wcag-technique:H25']),
    inputAspects: Object.freeze(["DOM Tree", "Language"]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 1, total: 6 }),
  }),
  Object.freeze({
    id: 'c5a4ea',
    name: "Video element visual content has accessible alternative",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.2.3', '1.2.5', '1.2.8']),
    otherRequirements: Object.freeze(['wcag-technique:G173', 'wcag-technique:G69', 'wcag-technique:G78', 'wcag-technique:G8']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 2, total: 9 }),
  }),
  Object.freeze({
    id: 'cae760',
    name: "Iframe element has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 4, inapplicable: 3, total: 10 }),
  }),
  Object.freeze({
    id: 'cc0f0a',
    name: "Form field label is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.6']),
    otherRequirements: Object.freeze(['wcag-technique:G131']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 6, failed: 5, inapplicable: 3, total: 14 }),
  }),
  Object.freeze({
    id: 'cf77f2',
    name: "Bypass Blocks of Repeated Content",
    ruleType: 'composite',
    successCriteria: Object.freeze(['2.4.1']),
    otherRequirements: Object.freeze(['wcag-technique:G1', 'wcag-technique:G123', 'wcag-technique:G124', 'wcag-technique:H69', 'wcag-technique:SCR28']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 12, failed: 1, inapplicable: 1, total: 14 }),
  }),
  Object.freeze({
    id: 'd0f69e',
    name: "Table header cell has assigned cells",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 6, failed: 3, inapplicable: 7, total: 16 }),
  }),
  Object.freeze({
    id: 'd7ba54',
    name: "Video element visual-only content has audio track alternative",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G166']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 2, inapplicable: 2, total: 5 }),
  }),
  Object.freeze({
    id: 'de46e4',
    name: "Element with lang attribute has valid language tag",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:H58']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS Styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 5, failed: 9, inapplicable: 5, total: 19 }),
  }),
  Object.freeze({
    id: 'e086e5',
    name: "Form field has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '2.5.3', '4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 7, failed: 7, inapplicable: 3, total: 17 }),
  }),
  Object.freeze({
    id: 'e6952f',
    name: "Attribute is not duplicated",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:H94']),
    inputAspects: Object.freeze(["Source code"]),
    testCases: Object.freeze({ passed: 5, failed: 3, inapplicable: 2, total: 10 }),
  }),
  Object.freeze({
    id: 'e7aa44',
    name: "Audio element content has text alternative",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.2.1']),
    otherRequirements: Object.freeze(['wcag-technique:G158']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 3, failed: 2, inapplicable: 3, total: 8 }),
  }),
  Object.freeze({
    id: 'e88epe',
    name: "Image not in the accessibility tree is decorative",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "Accessibility tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 5, failed: 5, inapplicable: 10, total: 20 }),
  }),
  Object.freeze({
    id: 'eac66b',
    name: "Video element auditory content has accessible alternative",
    ruleType: 'composite',
    successCriteria: Object.freeze(['1.2.2']),
    otherRequirements: Object.freeze(['wcag-technique:G87', 'wcag-technique:G93', 'wcag-technique:H95']),
    inputAspects: Object.freeze([]),
    testCases: Object.freeze({ passed: 2, failed: 2, inapplicable: 2, total: 6 }),
  }),
  Object.freeze({
    id: 'ebe86a',
    name: "Focusable element has no keyboard trap via non-standard navigation",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 3, failed: 3, inapplicable: 1, total: 7 }),
  }),
  Object.freeze({
    id: 'ee13b5',
    name: "Video element visual-only content has transcript",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.2.1', '1.3.1']),
    otherRequirements: Object.freeze(['wcag-technique:G159']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 2, failed: 4, inapplicable: 2, total: 8 }),
  }),
  Object.freeze({
    id: 'efbfc7',
    name: "Text content that changes automatically can be paused, stopped or hidden",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 5, failed: 1, inapplicable: 5, total: 11 }),
  }),
  Object.freeze({
    id: 'f196ce',
    name: "Video element visual content has description track",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G78', 'wcag-technique:H96']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 1, inapplicable: 3, total: 5 }),
  }),
  Object.freeze({
    id: 'f51b46',
    name: "Video element auditory content has captions",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.2.1']),
    otherRequirements: Object.freeze(['wcag-technique:G87', 'wcag-technique:G93', 'wcag-technique:H95']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Visual output"]),
    testCases: Object.freeze({ passed: 2, failed: 4, inapplicable: 2, total: 8 }),
  }),
  Object.freeze({
    id: 'fd26cf',
    name: "Video element visual-only content is media alternative for text",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Audio output", "Language"]),
    testCases: Object.freeze({ passed: 1, failed: 4, inapplicable: 2, total: 7 }),
  }),
  Object.freeze({
    id: 'fd3a94',
    name: "Links with identical accessible names and same context serve equivalent purpose",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.4', '2.4.9']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 8, failed: 5, inapplicable: 6, total: 19 }),
  }),
  Object.freeze({
    id: 'ff89c9',
    name: "ARIA required context role",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 6, failed: 4, inapplicable: 5, total: 15 }),
  }),
  Object.freeze({
    id: 'ffbc54',
    name: "No keyboard shortcut uses only printable characters",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.1.4']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["DOM Tree"]),
    testCases: Object.freeze({ passed: 6, failed: 2, inapplicable: 2, total: 10 }),
  }),
  Object.freeze({
    id: 'ffd0e9',
    name: "Heading has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['aria12:namecalculation']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 5, failed: 8, inapplicable: 2, total: 15 }),
  }),
  Object.freeze({
    id: 'in6db8',
    name: "ARIA required ID references exist",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1', '4.1.2']),
    otherRequirements: Object.freeze(['aria12:propcharacteristic_value']),
    inputAspects: Object.freeze(["DOM Tree", "CSS Styling"]),
    testCases: Object.freeze({ passed: 0, failed: 0, inapplicable: 0, total: 0 }),
  }),
  Object.freeze({
    id: 'kb1m8s',
    name: "ARIA global properties not used where prohibited",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.3.1']),
    otherRequirements: Object.freeze(['aria12:prohibitedattributes', 'wcag-technique:ARIA5']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 0, failed: 0, inapplicable: 0, total: 0 }),
  }),
  Object.freeze({
    id: 'm6b1q3',
    name: "Menuitem has non-empty accessible name",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['4.1.2']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS Styling", "DOM Tree"]),
    testCases: Object.freeze({ passed: 4, failed: 2, inapplicable: 2, total: 8 }),
  }),
  Object.freeze({
    id: 'off6ek',
    name: "HTML element language subtag matches language",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.2']),
    otherRequirements: Object.freeze(['wcag-technique:H58']),
    inputAspects: Object.freeze(["DOM tree", "Accessibility tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 5, failed: 4, inapplicable: 5, total: 14 }),
  }),
  Object.freeze({
    id: 'oj04fd',
    name: "Element in sequential focus order has visible focus",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['2.4.7']),
    otherRequirements: Object.freeze([]),
    inputAspects: Object.freeze(["CSS styling", "DOM tree"]),
    testCases: Object.freeze({ passed: 4, failed: 1, inapplicable: 4, total: 9 }),
  }),
  Object.freeze({
    id: 'qt1vmo',
    name: "Image accessible name is descriptive",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['1.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:G94', 'wcag-technique:G95']),
    inputAspects: Object.freeze(["Accessibility Tree", "DOM Tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 3, failed: 3, inapplicable: 10, total: 16 }),
  }),
  Object.freeze({
    id: 'ucwvc8',
    name: "HTML page language subtag matches default language",
    ruleType: 'atomic',
    successCriteria: Object.freeze(['3.1.1']),
    otherRequirements: Object.freeze(['wcag-technique:H57']),
    inputAspects: Object.freeze(["DOM tree", "Accessibility tree", "CSS Styling", "Language"]),
    testCases: Object.freeze({ passed: 4, failed: 5, inapplicable: 6, total: 15 }),
  }),
  Object.freeze({
    id: 'ye5d6e',
    name: "Document has an instrument to move focus to non-repeated content",
    ruleType: 'atomic',
    successCriteria: Object.freeze([]),
    otherRequirements: Object.freeze(['wcag-technique:G1', 'wcag-technique:G123', 'wcag-technique:G124']),
    inputAspects: Object.freeze(["Accessibility Tree", "CSS styling", "DOM Tree", "Language"]),
    testCases: Object.freeze({ passed: 8, failed: 3, inapplicable: 1, total: 12 }),
  }),
]);
